# Generated by Django 5.1 on 2025-01-24 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estado'),
        ),
        migrations.CreateModel(
            name='motoboy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cnh', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('placa_moto', models.CharField(max_length=10, unique=True)),
                ('modelo_moto', models.CharField(max_length=100)),
                ('ano_moto', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)])),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('alocado', 'Alocado'), ('livre', 'Livre'), ('inativo', 'Inativo')], default='livre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.estado')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('id', 'cidade'), name='unique_bairro_id_cidade'),
        ),
    ]
