# Generated by Django 5.1 on 2025-04-07 15:35

import django.core.validators
import django.db.models.deletion
import motopro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='estabelecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.estado')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estado'),
        ),
        migrations.CreateModel(
            name='motoboy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[motopro.models.validate_cpf])),
                ('cnh', models.CharField(max_length=11, unique=True, validators=[motopro.models.validate_cnh])),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('placa_moto', models.CharField(max_length=10, unique=True, validators=[motopro.models.validate_placa])),
                ('modelo_moto', models.CharField(max_length=100)),
                ('ano_moto', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)])),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('alocado', 'Alocado'), ('livre', 'Livre'), ('inativo', 'Inativo'), ('em_viagem', 'Em viagem')], default='livre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ranking', models.CharField(choices=[('Novato', 'Novato'), ('Aspirante', 'Aspirante'), ('Bronze I', 'Bronze I'), ('Bronze II', 'Bronze II'), ('Prata I', 'Prata I'), ('Prata II', 'Prata II'), ('Ouro I', 'Ouro I'), ('Ouro II', 'Ouro II'), ('Platina I', 'Platina I'), ('Platina II', 'Platina II'), ('Diamante I', 'Diamante I'), ('Diamante II', 'Diamante II')], default='Novato', max_length=20)),
                ('aceitacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cancelamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('supervisor_aprovado', models.BooleanField(default=False)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.estado')),
            ],
        ),
        migrations.CreateModel(
            name='rankingMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Novato', 'Novato'), ('Aspirante', 'Aspirante'), ('Bronze I', 'Bronze I'), ('Bronze II', 'Bronze II'), ('Prata I', 'Prata I'), ('Prata II', 'Prata II'), ('Ouro I', 'Ouro I'), ('Ouro II', 'Ouro II'), ('Platina I', 'Platina I'), ('Platina II', 'Platina II'), ('Diamante I', 'Diamante I'), ('Diamante II', 'Diamante II')], default='Novato', max_length=100)),
                ('aceitação', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cancelamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bonus_por_entrega', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
            ],
        ),
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.estado')),
            ],
        ),
        migrations.CreateModel(
            name='vaga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.CharField(max_length=300)),
                ('data_da_vaga', models.DateTimeField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Preenchida'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='aberta', max_length=20)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='motopro.estabelecimento')),
                ('motoboy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaga', to='motopro.motoboy')),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='comissaomotopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='Pendente', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='motopro.motoboy')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='motopro.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='supervisorestabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.supervisor')),
            ],
            options={
                'unique_together': {('supervisor', 'estabelecimento')},
            },
        ),
        migrations.CreateModel(
            name='supervisormotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.supervisor')),
            ],
            options={
                'unique_together': {('supervisor', 'motoboy')},
            },
        ),
    ]
