# Generated by Django 5.1 on 2025-01-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'cidade'), name='unique_bairro_id_cidade')],
            },
        ),
    ]
