# Generated by Django 5.1 on 2025-01-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='finished_at',
        ),
    ]
