# Generated by Django 5.1 on 2025-01-22 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='Pendente', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='todos_estado',
            new_name='estado_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='bairro_id',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='bairro_id',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.CharField(choices=[('motoboy', 'Motoboy'), ('empresa', 'Empresa'), ('supervisor', 'Supervisor'), ('superuser', 'Super usuario')], default='superuser', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='ano_moto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='status',
            field=models.CharField(choices=[('alocado', 'Alocado'), ('livre', 'Livre'), ('inativo', 'Inativo')], default='livre', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Encerrada'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='Aberta', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('id', 'cidade')},
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('id', 'cidade'), name='pk_bairro_id_cidade'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='motoboy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='motopro.motoboy'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='motopro.vaga'),
        ),
    ]
