# Generated by Django 5.1 on 2025-01-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='nbairro',
            new_name='nbairro_id',
        ),
    ]
