# Generated by Django 5.1 on 2025-01-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='bairro_id',
        ),
    ]
