# Generated by Django 5.1 on 2025-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='outrotelefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='outrotelefone2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='segundonome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='telefone3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='telefone4',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
