# Generated by Django 5.1 on 2025-01-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='bairro_id',
            new_name='nbairro',
        ),
    ]
