# Generated by Django 5.1 on 2025-01-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_rename_nbairro_motoboy_nbairro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaomotoboy',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='categoriamotoboy',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='contratomotoboy',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='ano_moto',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='cidade_id',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='estado_id',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='modelo_moto',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='nbairro_id',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='placa_moto',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
