# Generated by Django 5.1 on 2025-04-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_motoboy_empresa_motoboy_outrotelefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoboyTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('segundo_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('celular3', models.CharField(blank=True, max_length=20, null=True)),
                ('celular4', models.CharField(blank=True, max_length=20, null=True)),
                ('outro_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('outro_telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('antigo_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('versao_antiga_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='ranking',
            field=models.CharField(choices=[('Novato', 'Novato'), ('Aspirante', 'Aspirante'), ('Bronze I', 'Bronze I'), ('Bronze II', 'Bronze II'), ('Bronze III', 'Bronze III'), ('Prata I', 'Prata I'), ('Prata II', 'Prata II'), ('Prata III', 'Prata III'), ('Ouro I', 'Ouro I'), ('Ouro II', 'Ouro II'), ('Ouro III', 'Ouro III'), ('Platina I', 'Platina I'), ('Platina II', 'Platina II'), ('Platina III', 'Platina III'), ('Diamante I', 'Diamante I'), ('Diamante II', 'Diamante II'), ('Diamante III', 'Diamante III')], default='Novato', max_length=20),
        ),
    ]
