# Generated by Django 5.1 on 2025-03-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_alter_bairro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro'),
            preserve_default=False,
        ),
    ]
