# Generated by Django 5.1 on 2025-01-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_avaliacao_avaliador_empresa_status_supervisor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='todos_estado',
            new_name='estado_is',
        ),
    ]
