# Generated by Django 5.1 on 2025-01-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_candidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro_id',
            field=models.IntegerField(null=True),
        ),
    ]
