# Generated by Django 5.1 on 2025-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_remove_empresa_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
