# Generated by Django 5.1 on 2025-01-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_remove_bairro_unique_bairro_id_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'managed': False},
        ),
    ]
