# Generated by Django 5.1 on 2025-01-24 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0002_rename_nbairro_motoboy_nbairro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='nbairro_id',
        ),
        migrations.AddField(
            model_name='motoboy',
            name='nbairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motopro.bairro'),
            preserve_default=False,
        ),
    ]
