# Generated by Django 5.1 on 2025-04-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_motoboytemp_alter_motoboy_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotoboyTemp',
        ),
    ]
