# Generated by Django 5.1 on 2025-02-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_alter_bairro_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='empresa',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='empresa',
            new_name='estabelecimento',
        ),
    ]
