# Generated by Django 5.1 on 2025-01-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_remove_motoboy_nbairro_id_motoboy_nbairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy',
            name='nbairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro'),
        ),
    ]
