# Generated by Django 5.1 on 2025-01-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_motoboy_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='bairro_id',
        ),
    ]
