# Generated by Django 5.1 on 2025-01-22 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_empresa_bairro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='bairro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro'),
        ),
    ]
