# Generated by Django 5.1 on 2025-01-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_rename_todos_estado_cidade_estado_is'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='estado_is',
            new_name='estado_id',
        ),
    ]
