# Generated by Django 5.1 on 2025-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0003_supervisor_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Preencida'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='Aberta', max_length=20),
        ),
    ]
