# Generated by Django 5.1 on 2025-01-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0004_rename_estado_is_cidade_estado_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('id', 'cidade')},
        ),
    ]
