# Generated by Django 5.1 on 2025-02-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0004_rename_empresa_estabeleciomento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
            ],
        ),
    ]
