# Generated by Django 5.1 on 2025-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0004_vaga_hora_fim_vaga_hora_inicio_alter_vaga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='turno',
            field=models.CharField(blank=True, choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20, null=True),
        ),
    ]
