# Generated by Django 5.1 on 2025-01-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0004_remove_motoboy_bairro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='motopro.bairro'),
            preserve_default=False,
        ),
    ]
