# Generated by Django 5.1 on 2025-04-11 07:13

import motopro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0004_delete_motoboytemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy',
            name='cnh',
            field=models.CharField(max_length=11, validators=[motopro.models.validate_cnh]),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='cpf',
            field=models.CharField(max_length=11, validators=[motopro.models.validate_cpf]),
        ),
    ]
