# Generated by Django 5.1 on 2025-02-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supervisor',
        ),
    ]
