# Generated by Django 5.1 on 2025-02-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisorestabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.supervisor')),
            ],
            options={
                'unique_together': {('supervisor', 'estabelecimento')},
            },
        ),
        migrations.CreateModel(
            name='supervisormotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.supervisor')),
            ],
            options={
                'unique_together': {('supervisor', 'motoboy')},
            },
        ),
    ]
