# Generated by Django 5.1 on 2025-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_alter_bairro_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('id', 'cidade'), name='unique_bairro_per_city'),
        ),
    ]
