# Generated by Django 5.1 on 2025-02-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='deadline',
        ),
    ]
