# Generated by Django 5.1 on 2025-04-11 07:14

import motopro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_alter_motoboy_cnh_alter_motoboy_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy',
            name='placa_moto',
            field=models.CharField(max_length=10, validators=[motopro.models.validate_placa]),
        ),
    ]
