# Generated by Django 5.1 on 2025-01-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_motoboy_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='bairro',
            new_name='bairro_id',
        ),
    ]
