# Generated by Django 5.1 on 2025-03-31 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0005_vaga_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga')),
            ],
        ),
    ]
