# Generated by Django 5.1 on 2025-02-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0006_remove_supervisor_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='status',
        ),
    ]
