# Generated by Django 5.1 on 2025-03-31 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0006_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='comissaomotopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='rankingMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Novato', 'Novato'), ('Aspirante', 'Aspirante'), ('Bronze I', 'Bronze I'), ('Bronze II', 'Bronze II'), ('Prata I', 'Prata I'), ('Prata II', 'Prata II'), ('Ouro I', 'Ouro I'), ('Ouro II', 'Ouro II'), ('Platina I', 'Platina I'), ('Platina II', 'Platina II'), ('Diamante I', 'Diamante I'), ('Diamante II', 'Diamante II')], default='Novato', max_length=100)),
                ('aceitação', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cancelamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bonus_por_entrega', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
            ],
        ),
    ]
