# Generated by Django 5.1 on 2025-04-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0006_alter_motoboy_placa_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='estabelecimentocontrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('dia', 'Turno do Dia'), ('noite', 'Turno da Noite')], max_length=10)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('quantidade_vagas', models.PositiveIntegerField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimento')),
            ],
        ),
    ]
