# Generated by Django 5.1 on 2025-01-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0006_alter_bairro_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('id', 'cidade')},
        ),
    ]
