# Generated by Django 5.1 on 2025-02-18 03:53

import motopro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0006_supervisorestabelecimento_supervisormotoboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy',
            name='cnh',
            field=models.CharField(max_length=11, unique=True, validators=[motopro.models.validate_cnh]),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[motopro.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='placa_moto',
            field=models.CharField(max_length=10, unique=True, validators=[motopro.models.validate_placa]),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='status',
            field=models.CharField(choices=[('alocado', 'Alocado'), ('livre', 'Livre'), ('inativo', 'Inativo'), ('em_viagem', 'Em viagem')], default='livre', max_length=20),
        ),
    ]
