# Generated by Django 5.1 on 2025-02-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0007_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={},
        ),
    ]
