# Generated by Django 5.1 on 2025-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0007_estabelecimentocontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='turno',
        ),
        migrations.AddField(
            model_name='vaga',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
