# Generated by Django 5.1 on 2025-01-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0007_alter_bairro_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='bairro_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='bairro_id',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='bairro_id',
        ),
        migrations.DeleteModel(
            name='bairro',
        ),
    ]
