# Generated by Django 5.1 on 2025-04-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0008_remove_vaga_turno_vaga_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='observacoes',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='valor',
            new_name='valor_atribuido',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='quantidade',
        ),
    ]
