# Generated by Django 5.1 on 2025-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0008_alter_bairro_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='estado',
        ),
        migrations.RemoveConstraint(
            model_name='bairro',
            name='pk_bairro_id_cidade',
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('nome', 'cidade'), name='unique_bairro_cidade'),
        ),
        migrations.DeleteModel(
            name='supervisor',
        ),
    ]
