# Generated by Django 5.1 on 2025-03-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0008_motoboy_aceitação_motoboy_cancelamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='aceitação',
            new_name='aceitacao',
        ),
    ]
