# Generated by Django 5.1 on 2025-01-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0008_remove_supervisor_bairro_id_remove_empresa_bairro_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'cidade'), name='unique_bairro_per_city')],
                'unique_together': {('id', 'cidade')},
            },
        ),
    ]
