# Generated by Django 5.1 on 2025-04-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0009_rename_observacoes_vaga_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='hora_inicio',
        ),
    ]
