# Generated by Django 5.1 on 2025-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0009_rename_aceitação_motoboy_aceitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Preenchida'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='aberta', max_length=20),
        ),
    ]
