# Generated by Django 5.1 on 2025-01-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0009_bairro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bairro',
        ),
    ]
