# Generated by Django 5.1 on 2025-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0010_remove_vaga_hora_fim_remove_vaga_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='valor_atribuido',
        ),
        migrations.AddField(
            model_name='estabelecimentocontrato',
            name='valor_atribuido',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
