# Generated by Django 5.1 on 2025-04-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0010_alter_vaga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Preencida'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='Aberta', max_length=20),
        ),
    ]
