# Generated by Django 5.1 on 2025-01-22 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0010_delete_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'cidade'), name='unique_bairro_per_city')],
                'unique_together': {('id', 'cidade')},
            },
        ),
    ]
