# Generated by Django 5.1 on 2025-04-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0011_alter_vaga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='motoboy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaga', to='motopro.motoboy'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('preenchida', 'Preenchida'), ('encerrada', 'Encerrada'), ('recusada', 'Recusada')], default='aberta', max_length=20),
        ),
        migrations.DeleteModel(
            name='candidatura',
        ),
    ]
