# Generated by Django 5.1 on 2025-01-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0011_alter_cidade_id_bairro'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bairro',
            name='unique_bairro_per_city',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('id', 'cidade'), name='pk_bairro_id_cidade'),
        ),
    ]
