# Generated by Django 5.1 on 2025-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0011_remove_vaga_valor_atribuido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentocontrato',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('encerrada', 'Encerrada'), ('blqueado', 'Bloqueado')], default='aberta', max_length=20),
        ),
    ]
