# Generated by Django 5.1 on 2025-01-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0012_remove_bairro_unique_bairro_per_city_alter_bairro_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bairro',
        ),
    ]
