# Generated by Django 5.1 on 2025-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0013_alter_estabelecimentocontrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimentocontrato',
            name='turno',
            field=models.CharField(choices=[('dia', 'Turno do Dia'), ('noite', 'Turno da Noite'), ('madrugada', 'Turno da Madrugada')], max_length=10),
        ),
    ]
