# Generated by Django 5.1 on 2025-01-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0013_delete_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='bairro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.cidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'cidade'), name='pk_bairro_id_cidade')],
                'unique_together': {('id', 'cidade')},
            },
        ),
    ]
