# Generated by Django 5.1 on 2025-04-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0014_alter_estabelecimentocontrato_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_padrao', models.CharField(choices=[('dia', 'Turno do Dia'), ('noite', 'Turno da Noite')], default='dia', max_length=10)),
                ('horario_inicio_padrao', models.TimeField(default='08:00')),
                ('horario_fim_padrao', models.TimeField(default='18:00')),
                ('valor_padrao_por_vaga', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('sistema_ativo', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('versao', models.CharField(default='1.0.0', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimentocontrato'),
        ),
    ]
