# Generated by Django 5.1 on 2025-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0015_configuracao_vaga_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
