# Generated by Django 5.1 on 2025-04-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0016_alter_vaga_observacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='empresa',
            new_name='apelido',
        ),
    ]
