# Generated by Django 5.1 on 2025-04-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0017_rename_empresa_motoboy_apelido'),
    ]

    operations = [
        migrations.CreateModel(
            name='alocacaomotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('alocado', 'Alocado')], default='livre', max_length=20)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.motoboy')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimentocontrato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga')),
            ],
            options={
                'unique_together': {('motoboy', 'vaga', 'turno')},
            },
        ),
    ]
