# Generated by Django 5.1 on 2025-04-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0018_alocacaomotoboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='motoboy',
        ),
    ]
