# Generated by Django 5.1 on 2025-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0019_remove_vaga_motoboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_da_vaga',
            field=models.DateField(blank=True, null=True),
        ),
    ]
