# Generated by Django 5.1 on 2025-04-23 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0021_remove_vaga_estabelecimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidatura',
            new_name='candidaturamotoboy',
        ),
        migrations.AddField(
            model_name='estabelecimentocontrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimentocontrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='estabelecimentofatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida')], default='aberta', max_length=20)),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimento')),
            ],
        ),
        migrations.DeleteModel(
            name='entrega',
        ),
    ]
