# Generated by Django 5.1 on 2025-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0022_rename_candidatura_candidaturamotoboy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingmotoboy',
            old_name='aceitação',
            new_name='aceitacao',
        ),
        migrations.AddField(
            model_name='estabelecimentofatura',
            name='quantidade_alocacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
