# Generated by Django 5.1 on 2025-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0023_rename_aceitação_rankingmotoboy_aceitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaomotoboy',
            name='entregas_realizadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
