# Generated by Django 5.1 on 2025-04-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0024_alocacaomotoboy_entregas_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='categoria',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
