# Generated by Django 5.1 on 2025-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0025_motoboy_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='outrotelefone',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='outrotelefone2',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='segundonome',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='telefone3',
        ),
        migrations.RemoveField(
            model_name='motoboy',
            name='telefone4',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(default=99, max_length=18, unique=False),
            preserve_default=False,
        ),
    ]
