# Generated by Django 5.1 on 2025-04-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0026_remove_motoboy_outrotelefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='cnpj',
        ),
    ]
