# Generated by Django 5.1 on 2025-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0027_remove_estabelecimento_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(default=999, max_length=18),
            preserve_default=False,
        ),
    ]
