# Generated by Django 5.1 on 2025-04-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0029_slot_candidaturaslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimentocontrato')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motopro.motoboy')),
            ],
            options={
                'unique_together': {('contrato', 'data', 'hora_inicio')},
            },
        ),
    ]
