# Generated by Django 5.1 on 2025-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0030_vagaslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estabelecimentocontrato',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('encerrada', 'Encerrada'), ('bloqueado', 'Bloqueado')], default='vigente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20),
        ),
    ]
