# Generated by Django 5.1 on 2025-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0032_motoboy_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
