# Generated by Django 5.1 on 2025-04-30 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0033_nivelmotoboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy',
            name='ranking',
        ),
        migrations.AddField(
            model_name='motoboy',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='motopro.nivelmotoboy'),
            preserve_default=False,
        ),
    ]
