# Generated by Django 5.1 on 2025-04-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0034_remove_motoboy_ranking_motoboy_nivel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidaturaSlot',
            new_name='Slot_Candidatura',
        ),
        migrations.RenameModel(
            old_name='VagaSlot',
            new_name='Slot_Vaga',
        ),
    ]
