# Generated by Django 5.1 on 2025-04-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0035_rename_candidaturaslot_slot_candidatura_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estabelecimentocontrato',
            new_name='Estabelecimento_Contrato',
        ),
        migrations.RenameModel(
            old_name='estabelecimentofatura',
            new_name='Estabelecimento_Fatura',
        ),
        migrations.RenameModel(
            old_name='alocacaomotoboy',
            new_name='Motoboy_Alocacao',
        ),
        migrations.RenameModel(
            old_name='candidaturamotoboy',
            new_name='Motoboy_Candidatura',
        ),
        migrations.RenameModel(
            old_name='NivelMotoboy',
            new_name='Motoboy_Nivel',
        ),
        migrations.RenameModel(
            old_name='rankingMotoboy',
            new_name='Motoboy_Ranking',
        ),
        migrations.RenameModel(
            old_name='supervisorestabelecimento',
            new_name='Supervisor_Estabelecimento',
        ),
        migrations.RenameModel(
            old_name='supervisormotoboy',
            new_name='Supervisor_Motoboy',
        ),
       
    ]
