# Generated by Django 5.1 on 2025-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0036_rename_estabelecimentocontrato_estabelecimento_contrato_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comissaomotopro',
        ),
    ]
