# Generated by Django 5.1 on 2025-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0037_delete_comissaomotopro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave_sistema', models.SlugField(help_text='Chave usada pelo sistema para leitura do item', unique=True)),
                ('tipo_dado', models.CharField(choices=[('boolean', 'Booleano'), ('integer', 'Inteiro'), ('string', 'Texto'), ('float', 'Decimal')], max_length=10)),
                ('valor_padrao', models.CharField(blank=True, max_length=100, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
            ],
        ),
    ]
