# Generated by Django 5.1 on 2025-04-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0038_contratoitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratoItem',
            new_name='Contrato_Item',
        ),
    ]
