# Generated by Django 5.1 on 2025-04-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0039_rename_contratoitem_contrato_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento_Contrato_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='motopro.estabelecimento_contrato')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.contrato_item')),
            ],
            options={
                'unique_together': {('contrato', 'item')},
            },
        ),
    ]
