# Generated by Django 5.1 on 2025-04-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0040_estabelecimento_contrato_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento_contrato',
            name='estabelecimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motopro.estabelecimento'),
        ),
    ]
