# Generated by Django 5.1 on 2025-04-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0041_alter_estabelecimento_contrato_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento_contrato',
            name='turno',
        ),
    ]
