# Generated by Django 5.1 on 2025-04-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0043_remove_estabelecimento_contrato_quantidade_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento_contrato',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='estabelecimento_contrato',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='estabelecimento_contrato',
            name='valor_atribuido',
        ),
    ]
