# Generated by Django 5.1 on 2025-04-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0044_remove_estabelecimento_contrato_horario_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria_semanal', models.IntegerField(help_text='Horas por semana')),
                ('tipo_contrato', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('Intermitente', 'Intermitente'), ('Freelancer', 'Freelancer')], max_length=50)),
                ('descricao_atividades', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='motopro.motoboy')),
            ],
        ),
    ]
