# Generated by Django 5.1 on 2025-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0045_motoboy_contrato'),
    ]

    operations = [
             
        
         migrations.AddField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(blank=True, choices=[('fixa', 'Fixa'), ('spot', 'Spot')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Slot_Candidatura',
        ),
        migrations.DeleteModel(
            name='Slot_Vaga',
        ),
    ]
