# Generated by Django 5.1 on 2025-05-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0046_remove_slot_candidatura_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motoboy_alocacao',
            unique_together={('motoboy', 'vaga')},
        ),
        migrations.AddField(
            model_name='vaga',
            name='horario_fim_padrao',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='horario_inicio_padrao',
            field=models.TimeField(default='08:00'),
        ),
        migrations.RemoveField(
            model_name='motoboy_alocacao',
            name='turno',
        ),
    ]
