# Generated by Django 5.1 on 2025-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0049_alter_vaga_hora_fim_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('reservada', 'Reservada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
