# Generated by Django 5.1 on 2025-05-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0050_alter_vaga_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motoboy_Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField(help_text='Motivo do desconto ou observações')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicado_por', models.CharField(help_text='Nome do responsável pelo desconto', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descontos', to='motopro.categoria_desconto')),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='motopro.motoboy')),
            ],
        ),
    ]
