# Generated by Django 5.1 on 2025-05-05 15:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0051_categoria_desconto_motoboy_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento_contrato',
            name='valor_vaga_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da Vaga Fixa'),
        ),
        migrations.AddField(
            model_name='estabelecimento_contrato',
            name='valor_vaga_spot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da Vaga Spot'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(blank=True, choices=[('fixa', 'Fixa'), ('spot', 'Spot'), ('extra', 'Tele Extra')], max_length=10, null=True),
        ),
    ]
