# Generated by Django 5.1 on 2025-05-05 16:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0052_estabelecimento_contrato_valor_vaga_fixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento_contrato',
            name='valor_tele_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da Tele Extra'),
        ),
    ]
