# Generated by Django 5.1 on 2025-05-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0054_estabelecimento_fatura_valor_tele_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento_fatura',
            name='valor_vaga_extra',
        ),
    ]
