# Generated by Django 5.1 on 2025-05-05 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0055_remove_estabelecimento_fatura_valor_vaga_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento_fatura',
            name='valor_tele_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estabelecimento_fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estabelecimento_fatura',
            name='valor_vaga_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estabelecimento_fatura',
            name='valor_vaga_spot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
