# Generated by Django 5.1 on 2025-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0056_alter_estabelecimento_fatura_valor_tele_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('alocado', 'Alocado'), ('reservada', 'Reservada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
