# Generated by Django 5.1 on 2025-05-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0057_alter_vaga_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motoboy_alocacao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='motoboy_alocacao',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motopro.vaga'),
        ),
        migrations.RemoveField(
            model_name='motoboy_alocacao',
            name='status',
        ),
    ]
