# Generated by Django 5.1 on 2025-05-09 22:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0058_alter_motoboy_alocacao_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('alocado', 'Alocado'), ('finalizada', 'Finalizada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='Motoboy_Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data a que se refere o adiantamento (ex: dia do serviço)')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tipo_adiantamento', models.CharField(choices=[('adiantamento', ' Adiantamento'), ('fixo', 'Adiantamento Fixo'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='adiantamento', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='motopro.motoboy')),
            ],
            options={
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Motoboy_BandaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_km', models.PositiveSmallIntegerField(choices=[(6, '6 km'), (7, '7 km'), (8, '8 km'), (9, '9 km'), (10, '10 km'), (11, '11 km'), (12, '12 km'), (13, '13 km'), (14, '14 km'), (15, '15 km')])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas', to='motopro.motoboy_alocacao')),
            ],
            options={
                'unique_together': {('alocacao', 'faixa_km')},
            },
        ),
    ]
