# Generated by Django 5.1 on 2025-05-08 22:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0058_alter_motoboy_alocacao_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy_Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data a que se refere o repasse (ex: dia do serviço)')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tipo_repasse', models.CharField(choices=[('fixo', 'Repasse Fixo'), ('extra', 'Repasse Extra'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='fixo', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to='motopro.motoboy')),
            ],
            options={
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
