# Generated by Django 5.1 on 2025-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0059_motoboy_repasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy_repasse',
            name='tipo_repasse',
            field=models.CharField(choices=[('fixo', 'Repasse Fixo'), ('adiantamento', 'Repasse de Adiantamento'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='fixo', max_length=20),
        ),
    ]
