# Generated by Django 5.1 on 2025-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0059_alter_vaga_status_motoboy_adiantamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy_adiantamento',
            name='tipo_adiantamento',
            field=models.CharField(choices=[('adiantamento', ' Adiantamento'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='adiantamento', max_length=20),
        ),
    ]
