# Generated by Django 5.1 on 2025-05-11 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0060_alter_motoboy_adiantamento_tipo_adiantamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy_Contrato_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='motopro.motoboy_contrato')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motopro.contrato_item')),
            ],
        ),
    ]
