# Generated by Django 5.1 on 2025-05-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0060_alter_motoboy_repasse_tipo_repasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy_repasse',
            name='tipo_repasse',
            field=models.CharField(choices=[('adiantamento', 'Repasse de Adiantamento'), ('fixo', 'Repasse Fixo'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='adiantamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('alocado', 'Alocado'), ('finalizada', 'Finalizada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='Motoboy_BandaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_km', models.PositiveSmallIntegerField(choices=[(6, '6 km'), (7, '7 km'), (8, '8 km'), (9, '9 km'), (10, '10 km')])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas', to='motopro.motoboy_alocacao')),
            ],
            options={
                'unique_together': {('alocacao', 'faixa_km')},
            },
        ),
    ]
