# Generated by Django 5.1 on 2025-05-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0061_motoboy_contrato_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoboy_contrato',
            name='carga_horaria_semanal',
        ),
        migrations.RemoveField(
            model_name='motoboy_contrato',
            name='valor_mensal',
        ),
    ]
