# Generated by Django 5.1 on 2025-05-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0062_remove_motoboy_contrato_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy_contrato',
            name='descricao_atividades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
