# Generated by Django 5.1 on 2025-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0063_alter_motoboy_contrato_descricao_atividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboy',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('alocado', 'Alocado'), ('livre', 'Livre'), ('inativo', 'Inativo'), ('em_viagem', 'Em viagem')], default='inativo', max_length=20),
        ),
    ]
