# Generated by Django 5.1 on 2025-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0064_alter_motoboy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoIfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='motoboy_adiantamento',
            name='tipo_adiantamento',
            field=models.CharField(choices=[('adiantamento', ' Adiantamento'), ('bonus', 'Bônus'), ('ajuste', 'Ajuste Manual'), ('ajuste', 'Ajuste Manual'), ('outro', 'Outro')], default='adiantamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('alocado', 'Alocado'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('paga', 'Paga')], default='aberta', max_length=20),
        ),
    ]
