# Generated by Django 5.1 on 2025-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0065_pedidoifood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.CharField(help_text='Formato HH:MM', max_length=5)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
