# Generated by Django 5.1 on 2025-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0066_tarefaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfoodWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('order_id', models.UUIDField()),
                ('merchant_id', models.UUIDField()),
                ('code', models.CharField(max_length=10)),
                ('full_code', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoIfood',
        ),
    ]
