# Generated by Django 5.1 on 2025-05-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0067_ifoodwebhookevent_delete_pedidoifood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento_contrato_item',
            name='valor',
            field=models.CharField(max_length=40),
        ),
    ]
