# Generated by Django 5.1 on 2025-05-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0068_alter_estabelecimento_contrato_item_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True)),
                ('status_atribuicao', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=50)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='motopro.motoboy')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_motoboy', to='motopro.ifoodwebhookevent')),
            ],
        ),
    ]
