# Generated by Django 5.1 on 2025-05-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0069_pedidomotoboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifoodwebhookevent',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='pedidomotoboy',
            name='atribuido_em',
        ),
        migrations.AddField(
            model_name='ifoodwebhookevent',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidomotoboy',
            name='route_position',
            field=models.IntegerField(default=0),
        ),
    ]
