# Generated by Django 5.1 on 2025-05-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0070_remove_ifoodwebhookevent_received_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifoodwebhookevent',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='ifood_secret',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ifoodwebhookevent',
            name='endereco_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ifoodwebhookevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ifoodwebhookevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ifoodwebhookevent',
            name='motoboy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ifood_webhook_events', to='motopro.motoboy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidomotoboy',
            name='motoboy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_motoboy', to='motopro.motoboy'),
        ),
    ]
