# Generated by Django 5.1 on 2025-05-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0072_ifoodcustomer_ifoodorder_ifooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifoodorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ifooditem',
            name='order',
        ),
        migrations.DeleteModel(
            name='IfoodCustomer',
        ),
        migrations.DeleteModel(
            name='IfoodItem',
        ),
        migrations.DeleteModel(
            name='IfoodOrder',
        ),
    ]
