# Generated by Django 5.1 on 2025-05-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0074_customer_deliveryaddress_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMotoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_position', models.IntegerField(default=0)),
                ('status_atribuicao', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=50)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_motoboy', to='motopro.motoboy')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_motoboy', to='motopro.order')),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoMotoboy',
        ),
    ]
