# Generated by Django 5.1 on 2025-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bairro',
            name='unique_bairro_id_cidade',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('id', 'cidade')},
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('id', 'cidade'), name='pk_bairro_id_cidade'),
        ),
    ]
